#!/usr/bin/env bash
# make domains
domain_check() {
	# list of subdomains
	local domain="$1"
	local subdomain="$2"

	result=$(dig "$subdomain.$domain" | awk '/^;; ANSWER SECTION:/{getline; print}')
	record_type=$(echo "$result" | awk '{print $4}')
	destination=$(echo "$result" | awk '{print $5}')

	echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [  $# -eq 1 ]; then
	my_domain="$1"
	domain_check "$my_domain" www
	domain_check "$my_domain" lb-01
	domain_check "$my_domain" web-01
	domain_check "$my_domain" web-02
elif [  $# -eq 2 ]; then
	my_domain="$1"
	my_subdomain="$2"
	domain_check "$my_domain" "$my_subdomain"
else
	exit 1
fi
