#!/usr/bin/env bash

if [[ $# -lt 4 ]]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

filepath=$1
ip=$2
username=$3
sshpath=$4

scp -o StrictHostKeyChecking=no -i "$sshpath" "$filepath" "$username@$ip:~/"

exit 0