#!/usr/bin/env bash
#Install nginx web server

sudo apt-get -y install nginx
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart