#!/usr/bin/env bash
#Install nginx web server

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo service nginx restart
sudo echo "Hello World!" > /usr/share/nginx/html/index.html
sudo service nginx restart
#still trying to fix