#!/usr/bin/env bash
#Redirection
sudo apt-get -y install nginx

chmod 777 /etc/nginx/sites-available/default
sudo echo "server {
    listen 80;
    listen [::]:80;
    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me/ {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default
service nginx start