#!/usr/bin/env bash
# Make another server

sudo apt-get update -y
sudo apt-get install nginx -y

sudo service nginx start

sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
touch /var/www/html/index.html

echo "Hello World!" > /var/www/html/index.html
sudo mkdir /var/www/error
sudo chown  "$USER":"$USER" /var/www/error/
echo "Ceci n'est pas une page" > /var/www/error/404.html
sudo chown  "$USER":"$USER" /etc/nginx/sites-available/

sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' /etc/nginx/sites-available/default
sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/error/; internal; }' /etc/nginx/sites-available/default

sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
