#!/usr/bin/env bash
# install haproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown "$USER":"$USER" /etc/haproxy/haproxy.cfg
echo "
frontend web-front
  bind *:80
  mode http
  default_backend web-backend
backend web-backend
  balance roundrobin
  server 375371-web-01 100.27.13.254:80 check
  server 375371-web-02 54.173.155.101:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart